name: portfolio
description: A simple portfolio about myself after working 5 months in flutter.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  google_fonts: ^3.0.1  
  flutter_svg: ^1.1.1+1  
  flutter_riverpod: ^1.0.4  
  flutter_staggered_grid_view: 0.6.2  
  url_launcher: ^6.1.5  
  scroll_to_index: ^3.0.1 
  http: ^0.13.5  
  visibility_detector: ^0.4.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter


  #flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/svg/

  fonts:
    - family: sfmono
      fonts:
        - asset: fonts/sfmono.otf
